name: Deploy to dev
on: push
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/syfotekster:${{ github.sha }}
jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build and publish Docker image
        env:
          NAME: syfotekster
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker build -t ${IMAGE} .
          docker push ${IMAGE}
      - uses: nais/deploy/actions/deploy@v1
        name: Deploy to dev-fss
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais-dev.yaml
